package net.dungeons;


import net.fabricmc.api.ModInitializer;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;



public class Dungeons implements ModInitializer {

    public static final ThinWallBlock brickwall = new BrickThinWall();
    public static final ThinWallBlock jailbars = new Jailbars();
    public static final ThinWallBlock acasiawall = new WoodWalls();
    public static final ThinWallBlock birchwall = new WoodWalls();
    public static final ThinWallBlock darkoakwall = new WoodWalls();
    public static final ThinWallBlock oakwall = new WoodWalls();
    public static final ThinWallBlock sprucewall = new WoodWalls();
    public static final ThinWallBlock acacia_planks = new BrickThinWall();

    public static final ThinWallBlock andesite = new BrickThinWall();
    public static final ThinWallBlock barrel_side = new BrickThinWall();
    public static final ThinWallBlock birch_planks = new BrickThinWall();
    public static final ThinWallBlock black_concrete = new BrickThinWall();
    public static final ThinWallBlock black_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock black_terracotta = new BrickThinWall();
    public static final ThinWallBlock black_wool = new BrickThinWall();
    public static final ThinWallBlock blue_concrete = new BrickThinWall();
    public static final ThinWallBlock blue_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock blue_terracotta = new BrickThinWall();
    public static final ThinWallBlock blue_wool = new BrickThinWall();
    public static final ThinWallBlock bricks = new BrickThinWall();
    public static final ThinWallBlock brown_concrete = new BrickThinWall();
    public static final ThinWallBlock brown_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock brown_mushroom_block = new BrickThinWall();
    public static final ThinWallBlock brown_shulker_box = new BrickThinWall();
    public static final ThinWallBlock brown_terracotta = new BrickThinWall();
    public static final ThinWallBlock clay = new BrickThinWall();
    public static final ThinWallBlock cobblestone = new BrickThinWall();
    public static final ThinWallBlock composter_bottom = new BrickThinWall();
    public static final ThinWallBlock composter_side = new BrickThinWall();
    public static final ThinWallBlock cracked_stone_bricks = new BrickThinWall();
    public static final ThinWallBlock cyan_concrete = new BrickThinWall();
    public static final ThinWallBlock cyan_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock cyan_terracotta = new BrickThinWall();
    public static final ThinWallBlock dark_oak_planks = new BrickThinWall();
    public static final ThinWallBlock daylight_detector_side = new BrickThinWall();
    public static final ThinWallBlock dead_bubble_coral_block = new BrickThinWall();
    public static final ThinWallBlock dead_fire_coral_block = new BrickThinWall();
    public static final ThinWallBlock dead_horn_coral_block = new BrickThinWall();
    public static final ThinWallBlock dead_tube_coral_block = new BrickThinWall();
    public static final ThinWallBlock dirt = new BrickThinWall();
    public static final ThinWallBlock end_stone = new BrickThinWall();
    public static final ThinWallBlock end_stone_bricks = new BrickThinWall();
    public static final ThinWallBlock granite = new BrickThinWall();
    public static final ThinWallBlock gray_concrete = new BrickThinWall();
    public static final ThinWallBlock gray_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock gray_shulker_box = new BrickThinWall();
    public static final ThinWallBlock green_concrete = new BrickThinWall();
    public static final ThinWallBlock green_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock jungle_planks = new BrickThinWall();
    public static final ThinWallBlock light_blue_concrete = new BrickThinWall();
    public static final ThinWallBlock light_blue_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock light_gray_concrete = new BrickThinWall();
    public static final ThinWallBlock light_gray_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock lime_concrete = new BrickThinWall();
    public static final ThinWallBlock lime_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock magenta_concrete = new BrickThinWall();
    public static final ThinWallBlock magenta_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock mossy_cobblestone = new BrickThinWall();
    public static final ThinWallBlock mossy_stone_bricks = new BrickThinWall();
    public static final ThinWallBlock oak_planks = new BrickThinWall();
    public static final ThinWallBlock orange_concrete = new BrickThinWall();
    public static final ThinWallBlock orange_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock pink_concrete = new BrickThinWall();
    public static final ThinWallBlock pink_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock polished_andesite = new BrickThinWall();
    public static final ThinWallBlock polished_diorite = new BrickThinWall();
    public static final ThinWallBlock polished_granite = new BrickThinWall();
    public static final ThinWallBlock purple_concrete = new BrickThinWall();
    public static final ThinWallBlock purple_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock quartz_block_bottom = new BrickThinWall();
    public static final ThinWallBlock red_concrete = new BrickThinWall();
    public static final ThinWallBlock red_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock smooth_stone = new BrickThinWall();
    public static final ThinWallBlock smooth_stone_slab_side = new BrickThinWall();
    public static final ThinWallBlock spruce_planks = new BrickThinWall();
    public static final ThinWallBlock stone = new BrickThinWall();
    public static final ThinWallBlock stonecutter_bottom = new BrickThinWall();
    public static final ThinWallBlock stone_bricks = new BrickThinWall();
    public static final ThinWallBlock white_concrete = new BrickThinWall();
    public static final ThinWallBlock white_concrete_powder = new BrickThinWall();
    public static final ThinWallBlock yellow_concrete = new BrickThinWall();
    public static final ThinWallBlock yellow_concrete_powder = new BrickThinWall();


    @Override
    public void onInitialize() {


        Registry.register(Registry.BLOCK, new Identifier("dungeons","brickwall"),brickwall);
        Registry.register(Registry.ITEM,new Identifier("dungeons","brickwall"), new BlockItem(brickwall, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK,new Identifier("dungeons", "jailbars"), jailbars);
        Registry.register(Registry.ITEM,new Identifier("dungeons","jailbars"), new BlockItem(jailbars, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","acasiawall"),acasiawall);
        Registry.register(Registry.ITEM,new Identifier("dungeons","acasiawall"), new BlockItem(acasiawall, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","birchwall"),birchwall);
        Registry.register(Registry.ITEM,new Identifier("dungeons","birchwall"), new BlockItem(birchwall, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","darkoakwall"),darkoakwall);
        Registry.register(Registry.ITEM,new Identifier("dungeons","darkoakwall"), new BlockItem(darkoakwall, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","oakwall"),oakwall);
        Registry.register(Registry.ITEM,new Identifier("dungeons","oakwall"), new BlockItem(oakwall, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","sprucewall"),sprucewall);
        Registry.register(Registry.ITEM,new Identifier("dungeons","sprucewall"), new BlockItem(sprucewall, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","acacia_planks"),acacia_planks);
        Registry.register(Registry.ITEM,new Identifier("dungeons","acacia_planks"), new BlockItem(acacia_planks, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","andesite"),andesite);
        Registry.register(Registry.ITEM,new Identifier("dungeons","andesite"), new BlockItem(andesite, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","barrel_side"),barrel_side);
        Registry.register(Registry.ITEM,new Identifier("dungeons","barrel_side"), new BlockItem(barrel_side, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","birch_planks"),birch_planks);
        Registry.register(Registry.ITEM,new Identifier("dungeons","birch_planks"), new BlockItem(birch_planks, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","black_concrete"),black_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","black_concrete"), new BlockItem(black_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","black_concrete_powder"),black_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","black_concrete_powder"), new BlockItem(black_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","black_terracotta"),black_terracotta);
        Registry.register(Registry.ITEM,new Identifier("dungeons","black_terracotta"), new BlockItem(black_terracotta, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","black_wool"),black_wool);
        Registry.register(Registry.ITEM,new Identifier("dungeons","black_wool"), new BlockItem(black_wool, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","blue_concrete"),blue_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","blue_concrete"), new BlockItem(blue_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","blue_concrete_powder"),blue_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","blue_concrete_powder"), new BlockItem(blue_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","blue_terracotta"),blue_terracotta);
        Registry.register(Registry.ITEM,new Identifier("dungeons","blue_terracotta"), new BlockItem(blue_terracotta, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","blue_wool"),blue_wool);
        Registry.register(Registry.ITEM,new Identifier("dungeons","blue_wool"), new BlockItem(blue_wool, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","bricks"),bricks);
        Registry.register(Registry.ITEM,new Identifier("dungeons","bricks"), new BlockItem(bricks, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","brown_concrete"),brown_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","brown_concrete"), new BlockItem(brown_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","brown_concrete_powder"),brown_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","brown_concrete_powder"), new BlockItem(brown_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","brown_mushroom_block"),brown_mushroom_block);
        Registry.register(Registry.ITEM,new Identifier("dungeons","brown_mushroom_block"), new BlockItem(brown_mushroom_block, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","brown_shulker_box"),brown_shulker_box);
        Registry.register(Registry.ITEM,new Identifier("dungeons","brown_shulker_box"), new BlockItem(brown_shulker_box, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","brown_terracotta"),brown_terracotta);
        Registry.register(Registry.ITEM,new Identifier("dungeons","brown_terracotta"), new BlockItem(brown_terracotta, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","clay"),clay);
        Registry.register(Registry.ITEM,new Identifier("dungeons","clay"), new BlockItem(clay, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","cobblestone"),cobblestone);
        Registry.register(Registry.ITEM,new Identifier("dungeons","cobblestone"), new BlockItem(cobblestone, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","composter_bottom"),composter_bottom);
        Registry.register(Registry.ITEM,new Identifier("dungeons","composter_bottom"), new BlockItem(composter_bottom, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","composter_side"),composter_side);
        Registry.register(Registry.ITEM,new Identifier("dungeons","composter_side"), new BlockItem(composter_side, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","cracked_stone_bricks"),cracked_stone_bricks);
        Registry.register(Registry.ITEM,new Identifier("dungeons","cracked_stone_bricks"), new BlockItem(cracked_stone_bricks, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","cyan_concrete"),cyan_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","cyan_concrete"), new BlockItem(cyan_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","cyan_concrete_powder"),cyan_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","cyan_concrete_powder"), new BlockItem(cyan_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","cyan_terracotta"),cyan_terracotta);
        Registry.register(Registry.ITEM,new Identifier("dungeons","cyan_terracotta"), new BlockItem(cyan_terracotta, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","dark_oak_planks"),dark_oak_planks);
        Registry.register(Registry.ITEM,new Identifier("dungeons","dark_oak_planks"), new BlockItem(dark_oak_planks, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","daylight_detector_side"),daylight_detector_side);
        Registry.register(Registry.ITEM,new Identifier("dungeons","daylight_detector_side"), new BlockItem(daylight_detector_side, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","dead_bubble_coral_block"),dead_bubble_coral_block);
        Registry.register(Registry.ITEM,new Identifier("dungeons","dead_bubble_coral_block"), new BlockItem(dead_bubble_coral_block, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","dead_fire_coral_block"),dead_fire_coral_block);
        Registry.register(Registry.ITEM,new Identifier("dungeons","dead_fire_coral_block"), new BlockItem(dead_fire_coral_block, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","dead_horn_coral_block"),dead_horn_coral_block);
        Registry.register(Registry.ITEM,new Identifier("dungeons","dead_horn_coral_block"), new BlockItem(dead_horn_coral_block, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","dead_tube_coral_block"),dead_tube_coral_block);
        Registry.register(Registry.ITEM,new Identifier("dungeons","dead_tube_coral_block"), new BlockItem(dead_tube_coral_block, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","dirt"),dirt);
        Registry.register(Registry.ITEM,new Identifier("dungeons","dirt"), new BlockItem(dirt, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","end_stone"),end_stone);
        Registry.register(Registry.ITEM,new Identifier("dungeons","end_stone"), new BlockItem(end_stone, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","end_stone_bricks"),end_stone_bricks);
        Registry.register(Registry.ITEM,new Identifier("dungeons","end_stone_bricks"), new BlockItem(end_stone_bricks, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","granite"),granite);
        Registry.register(Registry.ITEM,new Identifier("dungeons","granite"), new BlockItem(granite, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","gray_concrete"),gray_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","gray_concrete"), new BlockItem(gray_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","gray_concrete_powder"),gray_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","gray_concrete_powder"), new BlockItem(gray_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","gray_shulker_box"),gray_shulker_box);
        Registry.register(Registry.ITEM,new Identifier("dungeons","gray_shulker_box"), new BlockItem(gray_shulker_box, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","green_concrete"),green_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","green_concrete"), new BlockItem(green_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","green_concrete_powder"),green_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","green_concrete_powder"), new BlockItem(green_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","jungle_planks"),jungle_planks);
        Registry.register(Registry.ITEM,new Identifier("dungeons","jungle_planks"), new BlockItem(jungle_planks, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","light_blue_concrete"),light_blue_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","light_blue_concrete"), new BlockItem(light_blue_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","light_blue_concrete_powder"),light_blue_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","light_blue_concrete_powder"), new BlockItem(light_blue_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","light_gray_concrete"),light_gray_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","light_gray_concrete"), new BlockItem(light_gray_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","light_gray_concrete_powder"),light_gray_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","light_gray_concrete_powder"), new BlockItem(light_gray_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","lime_concrete"),lime_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","lime_concrete"), new BlockItem(lime_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","lime_concrete_powder"),lime_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","lime_concrete_powder"), new BlockItem(lime_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","magenta_concrete"),magenta_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","magenta_concrete"), new BlockItem(magenta_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","magenta_concrete_powder"),magenta_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","magenta_concrete_powder"), new BlockItem(magenta_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","mossy_cobblestone"),mossy_cobblestone);
        Registry.register(Registry.ITEM,new Identifier("dungeons","mossy_cobblestone"), new BlockItem(mossy_cobblestone, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","mossy_stone_bricks"),mossy_stone_bricks);
        Registry.register(Registry.ITEM,new Identifier("dungeons","mossy_stone_bricks"), new BlockItem(mossy_stone_bricks, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","oak_planks"),oak_planks);
        Registry.register(Registry.ITEM,new Identifier("dungeons","oak_planks"), new BlockItem(oak_planks, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","orange_concrete"),orange_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","orange_concrete"), new BlockItem(orange_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","orange_concrete_powder"),orange_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","orange_concrete_powder"), new BlockItem(orange_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","pink_concrete"),pink_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","pink_concrete"), new BlockItem(pink_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","pink_concrete_powder"),pink_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","pink_concrete_powder"), new BlockItem(pink_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","polished_andesite"),polished_andesite);
        Registry.register(Registry.ITEM,new Identifier("dungeons","polished_andesite"), new BlockItem(polished_andesite, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","polished_diorite"),polished_diorite);
        Registry.register(Registry.ITEM,new Identifier("dungeons","polished_diorite"), new BlockItem(polished_diorite, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","polished_granite"),polished_granite);
        Registry.register(Registry.ITEM,new Identifier("dungeons","polished_granite"), new BlockItem(polished_granite, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","purple_concrete"),purple_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","purple_concrete"), new BlockItem(purple_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","purple_concrete_powder"),purple_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","purple_concrete_powder"), new BlockItem(purple_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","quartz_block_bottom"),quartz_block_bottom);
        Registry.register(Registry.ITEM,new Identifier("dungeons","quartz_block_bottom"), new BlockItem(quartz_block_bottom, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","red_concrete"),red_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","red_concrete"), new BlockItem(red_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","red_concrete_powder"),red_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","red_concrete_powder"), new BlockItem(red_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","smooth_stone"),smooth_stone);
        Registry.register(Registry.ITEM,new Identifier("dungeons","smooth_stone"), new BlockItem(smooth_stone, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","smooth_stone_slab_side"),smooth_stone_slab_side);
        Registry.register(Registry.ITEM,new Identifier("dungeons","smooth_stone_slab_side"), new BlockItem(smooth_stone_slab_side, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","spruce_planks"),spruce_planks);
        Registry.register(Registry.ITEM,new Identifier("dungeons","spruce_planks"), new BlockItem(spruce_planks, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","stone"),stone);
        Registry.register(Registry.ITEM,new Identifier("dungeons","stone"), new BlockItem(stone, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","stonecutter_bottom"),stonecutter_bottom);
        Registry.register(Registry.ITEM,new Identifier("dungeons","stonecutter_bottom"), new BlockItem(stonecutter_bottom, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","stone_bricks"),stone_bricks);
        Registry.register(Registry.ITEM,new Identifier("dungeons","stone_bricks"), new BlockItem(stone_bricks, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","white_concrete"),white_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","white_concrete"), new BlockItem(white_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","white_concrete_powder"),white_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","white_concrete_powder"), new BlockItem(white_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","yellow_concrete"),yellow_concrete);
        Registry.register(Registry.ITEM,new Identifier("dungeons","yellow_concrete"), new BlockItem(yellow_concrete, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
        Registry.register(Registry.BLOCK, new Identifier("dungeons","yellow_concrete_powder"),yellow_concrete_powder);
        Registry.register(Registry.ITEM,new Identifier("dungeons","yellow_concrete_powder"), new BlockItem(yellow_concrete_powder, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));

    }
}
